// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AlertProvider, useAlert } from "@/context/AlertContext";
import _Alert_Msg from "@/app/components/Global/Elements/alert";
import {RecoilRoot} from "recoil";
import {Toaster} from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
                {children}
            <Toaster richColors/>
        </ThemeProvider>
        </body>
        </html>
    );
};

export default RootLayout;